sudo: false
dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
services: docker
before_install:
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
  - docker run -d -p 127.0.0.1:8500:8500 consul:latest
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

env:
  global:
    # CI_DEPLOY_USERNAME
    - secure: "Si7FrUAxJ1ZZlYWR9gLQxR3PJ1uCgi5fsw7aPZwA+XVsIkSZ1tGU0AHU3xpfOaXbx01A3EsSOXdDM6Y3MT7NaucL9vo8/cOAoJTAL71SXhUH73FYeHfzlvG7Ok2wf/kqqL9pWIKn2ucpYZiZw8QXYh+xGddbicJmTwH5NA1pZJ4sWUnhpQ6RFTGgJX1xIGWJ+A5Y1u6SHGXLiplPq1uwBpOZOoho8tO7AtGYtCh64Ns6/+wSyx/BFzKkb8jT6IfKZC3ZVLtlb9Y14iwi8L0+oeVIwPtNTymbVP0TH/iwAk9+7mJ3q/sl6Hx5672n2CjyWJVPzyKODs+O0DmVjEclAeiFLr+JJZkldzv9FXmZrt8WnKhHvwtpN5YzMFiD6qExl2cyd6NHSb0qeLzhWvNhSS0kPzalfr2xF7+tiGuDofUu9dOup5mcZYIk2IZtucSwHfRaphZfxvLWeAD5AdI2uSazTOdS/A/kDbwBjYVUxudElIYdZmZFxuxncdizN59ezAFqvj5MJ3EnW2Cv8HtIapnubVqH2fDrvLRYjQCxtnIKih6jMRKACsgIuewZjKcGvhQ7A5fkW9XD0vYYlMuE3b2m7x1MKrjewpeBJNDb10o9/bdytlsjDiJF7wq+en9B5yZJ+V2MxZ0y7/6/JCzb2WMM+KmGiUUrv0ThptE+KGI="
    # CI_DEPLOY_PASSWORD
    - secure: "Oh4nvjDBbZB4pTQ7eymrCt3BFXCcRt2EZkhq+ornXPwBXG6slALaaXekf2+CItv6U9223zBGFyfX3L7HVCzFO9ViHyUSnMjetcgru+/gQXzX6JBHBIxt/AdO4umoMcbwVzPTAXmZuuAvLyxKUFZdD5WnaJqTTKAkuTx8bsgeO6i3dnGNHg/PPJ+HQO0OU+MlVkIZB//jbV+RRmC8OcSJFNn88lwVdlocsS2i0i9piZ6CHknDYCzFSWoSGzY9U12HUaQeYkQSh8ipndtP9dRjr8fec5kOoyzS1Y7NzhkZ86/DKrm3Upvc16mRl8UWaUX1z9RRLn9WnBhNRezvJxFnKVX9AcufgcancENlrLpJ9ljZxW9O1DJKZtTNblIgWH7HSEzZeh1EE+2icgZQ9+N7Ei7REXSC1es+3ATADtUuol6Jd2VyuEr1d1pFtVKuuFTpMVCNtJxkb8Z0oSyLS0MUopd0JtNVl5pQn0FxwSDnwho6RzIsSLiDZWk1mtNGBA8lXv6RQamBgMBO9m9+dT7PHx7mO3YOc52dukrA0uhsJt7uvQlx/qR8ekHjy8Xq3Ni5lGqhw/rEjZvjZZKZRTvypC9CJi0zDZt8aR1qFlRL8Nb1v09e/qGBT7P6zqw1v8v2Jh+rEZnzcn1fHCmuIt14c3Pr4p3qiP9t0NkmAjcQUug="
